[workspace]
resolver = "3"
members = [
  "crates/calculus_of_constructions",
  "crates/parsers",
  "crates/simply_typed_lambda_calculus",
  "crates/system_f",
  "examples/calculus_of_constructions_repl",
  "examples/simply_typed_lambda_calculus_repl",
  "examples/system_f_repl",
]

[workspace.dependencies]
chumsky = "0.13.0"
ariadne = "0.6.0"
rustyline = "18.0.0"
indexmap = "2.14.0"
ignorable = "0.1.4"
